load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "ycsbt",
    srcs = ["ycsbt.go"],
    importpath = "github.com/cockroachdb/cockroach/pkg/workload/ycsbt",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/sql/pgwire/pgcode",
        "//pkg/sql/types",
        "//pkg/util/timeutil",
        "//pkg/workload",
        "//pkg/workload/histogram",
        "//pkg/workload/workloadimpl",
        "@com_github_cockroachdb_errors//:errors",
        "@com_github_jackc_pgx_v5//pgconn",
        "@com_github_spf13_pflag//:pflag",
    ],
)

go_test(
    name = "ycsbt_test",
    size = "small",
    srcs = ["ycsbt_test.go"],
    embed = [":ycsbt"],
    deps = [
        "//pkg/workload",
        "//pkg/workload/workloadimpl",
        "@com_github_stretchr_testify//require",
    ],
)
